{% set name = "trailrunner" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/trailrunner-{{ version }}.tar.gz
  sha256: 3fe61e259e6b2e5192f321c265985b7a0dc18497ced62b2da244f08104978398

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - flit-core >=3,<4
    - pathspec >=0.8.1
  run:
    - python >=3.7
    - pathspec >=0.8.1

test:
  imports:
    - trailrunner
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://trailrunner.omnilib.dev
  summary: Run things on paths
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dstoeckel
    - nicornk
